services:
  backend:
    build:
      context: ./backend
    container_name: mockmate-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
  
  frontend:
    build:
      context: ./frontend
    container_name: mockmate-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
